// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfHiTask = "wf_hi_task"

// WfHiTask mapped from table <wf_hi_task>
type WfHiTask struct {
	ID                string     `gorm:"column:id;primaryKey;comment:任务主键UUID" json:"id"`                          // 任务主键UUID
	ProcessInstanceID *string    `gorm:"column:process_instance_id;comment:流程实例ID" json:"processInstanceId"`       // 流程实例ID
	ProcessID         string     `gorm:"column:process_id;not null;comment:流程定义ID" json:"processId"`               // 流程定义ID
	TaskDefKey        *string    `gorm:"column:task_def_key;comment:任务节点ID" json:"taskDefKey"`                     // 任务节点ID
	TaskType          string     `gorm:"column:task_type;not null;default:user_task;comment:任务类型" json:"taskType"` // 任务类型
	Name              string     `gorm:"column:name;not null;comment:任务名称" json:"name"`                            // 任务名称
	Description       *string    `gorm:"column:description" json:"description"`
	ParentID          *string    `gorm:"column:parent_id" json:"parentId"`
	Status            string     `gorm:"column:status;not null;comment:状态：created | assigned | pending | active | delegated | suspended | completed | returned | withdrawn | terminated" json:"status"` // 状态：created | assigned | pending | active | delegated | suspended | completed | returned | withdrawn | terminated
	Assignee          *string    `gorm:"column:assignee;comment:办理人" json:"assignee"`                                                                                                                   // 办理人
	Owner             *string    `gorm:"column:owner" json:"owner"`
	DueDate           *time.Time `gorm:"column:due_date" json:"dueDate"`
	Priority          int32      `gorm:"column:priority;not null;default:50" json:"priority"`
	FormKey           *string    `gorm:"column:form_key" json:"formKey"`
	Variables         *string    `gorm:"column:variables;default:{};comment:任务变量" json:"variables"` // 任务变量
	ClaimedAt         *time.Time `gorm:"column:claimed_at" json:"claimedAt"`
	SequenceOrder     int32      `gorm:"column:sequence_order;not null;comment:会签序号（用于顺序会签排序，0表示主任务或非会签任务）" json:"sequenceOrder"` // 会签序号（用于顺序会签排序，0表示主任务或非会签任务）
	ApprovalType      string     `gorm:"column:approval_type;not null;default:single" json:"approvalType"`
	ApprovalRule      *string    `gorm:"column:approval_rule;default:{}" json:"approvalRule"`
	DelegateFrom      *string    `gorm:"column:delegate_from" json:"delegateFrom"`
	DelegateReason    *string    `gorm:"column:delegate_reason" json:"delegateReason"`
	DelegateTime      *time.Time `gorm:"column:delegate_time" json:"delegateTime"`
	EndedAt           *time.Time `gorm:"column:ended_at;comment:完成时间" json:"endedAt"`        // 完成时间
	Comment           *string    `gorm:"column:comment;comment:处理意见" json:"comment"`         // 处理意见
	EndReason         *string    `gorm:"column:end_reason;comment:完成/终止原因" json:"endReason"` // 完成/终止原因
	Duration          *int64     `gorm:"column:duration;comment:任务耗时（毫秒）" json:"duration"`   // 任务耗时（毫秒）
	TenantID          string     `gorm:"column:tenant_id;not null" json:"tenantId"`
	CreatedBy         string     `gorm:"column:created_by;not null" json:"createdBy"`
	CreatedAt         time.Time  `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedBy         *string    `gorm:"column:updated_by" json:"updatedBy"`
	UpdatedAt         *time.Time `gorm:"column:updated_at" json:"updatedAt"`
}

// TableName WfHiTask's table name
func (*WfHiTask) TableName() string {
	return TableNameWfHiTask
}
