// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfHiInstance = "wf_hi_instance"

// WfHiInstance mapped from table <wf_hi_instance>
type WfHiInstance struct {
	ID              string     `gorm:"column:id;primaryKey;comment:主键UUID" json:"id"`                                                                            // 主键UUID
	ProcessID       string     `gorm:"column:process_id;not null;comment:流程定义ID" json:"processId"`                                                               // 流程定义ID
	BusinessKey     *string    `gorm:"column:business_key;comment:业务键" json:"businessKey"`                                                                       // 业务键
	Name            string     `gorm:"column:name;not null;comment:实例名称" json:"name"`                                                                            // 实例名称
	StartUserID     string     `gorm:"column:start_user_id;not null;comment:流程发起人用户ID；系统触发时为空字符串" json:"startUserId"`                                            // 流程发起人用户ID；系统触发时为空字符串
	Status          string     `gorm:"column:status;not null;comment:生命周期状态：draft / active / completed / suspended / terminated/cancelled/failed" json:"status"` // 生命周期状态：draft / active / completed / suspended / terminated/cancelled/failed
	Variables       *string    `gorm:"column:variables;default:{};comment:流程变量" json:"variables"`                                                                // 流程变量
	CurrentActivity *string    `gorm:"column:current_activity;comment:最后停留节点" json:"currentActivity"`                                                            // 最后停留节点
	Priority        int32      `gorm:"column:priority;not null;default:50;comment:优先级" json:"priority"`                                                          // 优先级
	ParentID        *string    `gorm:"column:parent_id;comment:父流程实例ID" json:"parentId"`                                                                         // 父流程实例ID
	TenantID        string     `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenantId"`                                                                   // 租户ID
	CreatedBy       string     `gorm:"column:created_by;not null;comment:发起人" json:"createdBy"`                                                                  // 发起人
	CreatedAt       time.Time  `gorm:"column:created_at;not null;comment:实例创建时间" json:"createdAt"`                                                               // 实例创建时间
	UpdatedBy       *string    `gorm:"column:updated_by;comment:最后更新人" json:"updatedBy"`                                                                         // 最后更新人
	UpdatedAt       *time.Time `gorm:"column:updated_at;comment:最后更新时间" json:"updatedAt"`                                                                        // 最后更新时间
	EndReason       *string    `gorm:"column:end_reason;comment:完成/终止原因（包含错误信息）" json:"endReason"`                                                               // 完成/终止原因（包含错误信息）
	Duration        *int64     `gorm:"column:duration;comment:运行时长（毫秒）" json:"duration"`                                                                         // 运行时长（毫秒）
	EndedAt         *time.Time `gorm:"column:ended_at;comment:流程结束时间" json:"endedAt"`                                                                            // 流程结束时间
}

// TableName WfHiInstance's table name
func (*WfHiInstance) TableName() string {
	return TableNameWfHiInstance
}
