// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfInstance = "wf_instance"

// WfInstance mapped from table <wf_instance>
type WfInstance struct {
	ID              string     `gorm:"column:id;primaryKey;comment:主键UUID" json:"id"`                                                                                               // 主键UUID
	ProcessID       string     `gorm:"column:process_id;not null;comment:流程定义ID" json:"processId"`                                                                                  // 流程定义ID
	BusinessKey     *string    `gorm:"column:business_key;comment:业务键,业务系统唯一编号" json:"businessKey"`                                                                                 // 业务键,业务系统唯一编号
	Name            string     `gorm:"column:name;not null;comment:实例名称" json:"name"`                                                                                               // 实例名称
	StartUserID     string     `gorm:"column:start_user_id;not null;comment:流程发起人用户ID；系统触发时为空字符串" json:"startUserId"`                                                               // 流程发起人用户ID；系统触发时为空字符串
	Status          string     `gorm:"column:status;not null;default:active;comment:生命周期状态：draft / active / completed / suspended / terminated / cancelled / failed" json:"status"` // 生命周期状态：draft / active / completed / suspended / terminated / cancelled / failed
	Variables       *string    `gorm:"column:variables;default:{};comment:流程变量" json:"variables"`                                                                                   // 流程变量
	CurrentActivity *string    `gorm:"column:current_activity;comment:当前运行到的节点定义ID" json:"currentActivity"`                                                                         // 当前运行到的节点定义ID
	Priority        int32      `gorm:"column:priority;not null;default:50;comment:优先级（数值越大越优先）" json:"priority"`                                                                    // 优先级（数值越大越优先）
	ParentID        *string    `gorm:"column:parent_id;comment:父流程实例ID（用于子流程）" json:"parentId"`                                                                                     // 父流程实例ID（用于子流程）
	TenantID        string     `gorm:"column:tenant_id;not null;comment:租户ID（SaaS 多租户）" json:"tenantId"`                                                                            // 租户ID（SaaS 多租户）
	CreatedBy       string     `gorm:"column:created_by;not null;comment:发起人用户ID" json:"createdBy"`                                                                                 // 发起人用户ID
	CreatedAt       time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:实例创建时间" json:"createdAt"`                                                        // 实例创建时间
	UpdatedBy       *string    `gorm:"column:updated_by;comment:最后更新人" json:"updatedBy"`                                                                                            // 最后更新人
	UpdatedAt       *time.Time `gorm:"column:updated_at;comment:最后更新时间" json:"updatedAt"`                                                                                           // 最后更新时间
	EndReason       *string    `gorm:"column:end_reason;comment:完成/终止原因（包含错误信息）" json:"endReason"`                                                                                  // 完成/终止原因（包含错误信息）
	Duration        *int64     `gorm:"column:duration" json:"duration"`
	EndedAt         *time.Time `gorm:"column:ended_at" json:"endedAt"`
	Process         *WfProcess `gorm:"foreignKey:ProcessID;references:ID" json:"process"`

	// CurrentActivityName 当前节点名（按 CurrentActivity 节点 ID 从流程定义解析，
	// 解析失败回退节点 ID）。非持久化字段：列表/单条查询返回前由 RuntimeService
	// 装配（见 service/runtime_activity_name.go），不对应任何数据库列。
	// 手工新增字段：cmd/gen 重新生成本文件时会丢失，需在生成后补回
	// （gorm.io/gen 只按表列生成，无法声明虚拟字段）。
	CurrentActivityName string `gorm:"-" json:"currentActivityName,omitempty"`
}

// TableName WfInstance's table name
func (*WfInstance) TableName() string {
	return TableNameWfInstance
}
