// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfProcess = "wf_process"

// WfProcess mapped from table <wf_process>
type WfProcess struct {
	ID             string     `gorm:"column:id;primaryKey;comment:UUID 主键" json:"id"`                                               // UUID 主键
	ProcessKey     string     `gorm:"column:process_key;not null;comment:流程键（业务唯一标识）" json:"processKey"`                            // 流程键（业务唯一标识）
	Name           string     `gorm:"column:name;not null;comment:流程名称" json:"name"`                                                // 流程名称
	Version        int32      `gorm:"column:version;not null;comment:版本号（从 1 开始递增）" json:"version"`                                 // 版本号（从 1 开始递增）
	Category       *string    `gorm:"column:category;comment:分类（可用于权限/报表筛选）" json:"category"`                                       // 分类（可用于权限/报表筛选）
	Description    *string    `gorm:"column:description;comment:流程描述" json:"description"`                                           // 流程描述
	DefinitionJSON string     `gorm:"column:definition_json;not null;comment:流程定义DSL" json:"definitionJson"`                        // 流程定义DSL
	Status         string     `gorm:"column:status;not null;default:active;comment:状态：active=生效，retired=已停用" json:"status"`         // 状态：active=生效，retired=已停用
	PublishTime    time.Time  `gorm:"column:publish_time;not null;default:now();comment:版本发布时间" json:"publishTime"`                 // 版本发布时间
	Icon           string     `gorm:"column:icon;not null;comment:流程图标" json:"icon"`                                                // 流程图标
	ProcessType    string     `gorm:"column:process_type;not null;default:main;comment:流程定义类型：main 主流程、sub 子流程" json:"processType"` // 流程定义类型：main 主流程、sub 子流程
	TenantID       string     `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenantId"`                                      // 租户 ID
	CreatedBy      string     `gorm:"column:created_by;not null;comment:创建人" json:"createdBy"`                                      // 创建人
	CreatedAt      time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"`           // 创建时间
	UpdatedBy      *string    `gorm:"column:updated_by;comment:更新人" json:"updatedBy"`                                               // 更新人
	UpdatedAt      *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                              // 更新时间
	Ext            *string    `gorm:"column:ext;default:{};comment:结构化扩展字段" json:"ext"`                                             // 结构化扩展字段
}

// TableName WfProcess's table name
func (*WfProcess) TableName() string {
	return TableNameWfProcess
}
