// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfTaskComment = "wf_task_comment"

// WfTaskComment mapped from table <wf_task_comment>
type WfTaskComment struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	TaskID            string    `gorm:"column:task_id;not null;comment:任务实例 ID" json:"taskId"`                        // 任务实例 ID
	ProcessInstanceID string    `gorm:"column:process_instance_id;not null;comment:流程实例 ID" json:"processInstanceId"` // 流程实例 ID
	TenantID          string    `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenantId"`                      // 租户 ID
	UserID            string    `gorm:"column:user_id;not null;comment:评论人 ID" json:"userId"`                         // 评论人 ID
	UserName          string    `gorm:"column:user_name;not null;comment:评论人姓名" json:"userName"`                      // 评论人姓名
	Content           string    `gorm:"column:content;not null;comment:评论内容" json:"content"`                          // 评论内容
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
}

// TableName WfTaskComment's table name
func (*WfTaskComment) TableName() string {
	return TableNameWfTaskComment
}
