// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWfTaskAssignee = "wf_task_assignee"

// WfTaskAssignee mapped from table <wf_task_assignee>
type WfTaskAssignee struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	TaskID     string    `gorm:"column:task_id;not null;comment:任务实例 ID" json:"taskId"`                                          // 任务实例 ID
	EntityType string    `gorm:"column:entity_type;not null;default:role;comment:实体类型 role/department/person" json:"entityType"` // 实体类型 role/department/person
	EntityID   string    `gorm:"column:entity_id;not null;comment:实体 ID（roleId/deptId/userId）" json:"entityId"`                  // 实体 ID（roleId/deptId/userId）
	TenantID   string    `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenantId"`                                        // 租户 ID
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
}

// TableName WfTaskAssignee's table name
func (*WfTaskAssignee) TableName() string {
	return TableNameWfTaskAssignee
}
