// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	WfHiInstance   *wfHiInstance
	WfHiTask       *wfHiTask
	WfInstance     *wfInstance
	WfProcess      *wfProcess
	WfTask         *wfTask
	WfTaskAssignee *wfTaskAssignee
	WfTaskComment  *wfTaskComment
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	WfHiInstance = &Q.WfHiInstance
	WfHiTask = &Q.WfHiTask
	WfInstance = &Q.WfInstance
	WfProcess = &Q.WfProcess
	WfTask = &Q.WfTask
	WfTaskAssignee = &Q.WfTaskAssignee
	WfTaskComment = &Q.WfTaskComment
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		WfHiInstance:   newWfHiInstance(db, opts...),
		WfHiTask:       newWfHiTask(db, opts...),
		WfInstance:     newWfInstance(db, opts...),
		WfProcess:      newWfProcess(db, opts...),
		WfTask:         newWfTask(db, opts...),
		WfTaskAssignee: newWfTaskAssignee(db, opts...),
		WfTaskComment:  newWfTaskComment(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	WfHiInstance   wfHiInstance
	WfHiTask       wfHiTask
	WfInstance     wfInstance
	WfProcess      wfProcess
	WfTask         wfTask
	WfTaskAssignee wfTaskAssignee
	WfTaskComment  wfTaskComment
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		WfHiInstance:   q.WfHiInstance.clone(db),
		WfHiTask:       q.WfHiTask.clone(db),
		WfInstance:     q.WfInstance.clone(db),
		WfProcess:      q.WfProcess.clone(db),
		WfTask:         q.WfTask.clone(db),
		WfTaskAssignee: q.WfTaskAssignee.clone(db),
		WfTaskComment:  q.WfTaskComment.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		WfHiInstance:   q.WfHiInstance.replaceDB(db),
		WfHiTask:       q.WfHiTask.replaceDB(db),
		WfInstance:     q.WfInstance.replaceDB(db),
		WfProcess:      q.WfProcess.replaceDB(db),
		WfTask:         q.WfTask.replaceDB(db),
		WfTaskAssignee: q.WfTaskAssignee.replaceDB(db),
		WfTaskComment:  q.WfTaskComment.replaceDB(db),
	}
}

type queryCtx struct {
	WfHiInstance   IWfHiInstanceDo
	WfHiTask       IWfHiTaskDo
	WfInstance     IWfInstanceDo
	WfProcess      IWfProcessDo
	WfTask         IWfTaskDo
	WfTaskAssignee IWfTaskAssigneeDo
	WfTaskComment  IWfTaskCommentDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		WfHiInstance:   q.WfHiInstance.WithContext(ctx),
		WfHiTask:       q.WfHiTask.WithContext(ctx),
		WfInstance:     q.WfInstance.WithContext(ctx),
		WfProcess:      q.WfProcess.WithContext(ctx),
		WfTask:         q.WfTask.WithContext(ctx),
		WfTaskAssignee: q.WfTaskAssignee.WithContext(ctx),
		WfTaskComment:  q.WfTaskComment.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
