// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/rulego/gflow-engine/model"
)

func newWfHiTask(db *gorm.DB, opts ...gen.DOOption) wfHiTask {
	_wfHiTask := wfHiTask{}

	_wfHiTask.wfHiTaskDo.UseDB(db, opts...)
	_wfHiTask.wfHiTaskDo.UseModel(&model.WfHiTask{})

	tableName := _wfHiTask.wfHiTaskDo.TableName()
	_wfHiTask.ALL = field.NewAsterisk(tableName)
	_wfHiTask.ID = field.NewString(tableName, "id")
	_wfHiTask.ProcessInstanceID = field.NewString(tableName, "process_instance_id")
	_wfHiTask.ProcessID = field.NewString(tableName, "process_id")
	_wfHiTask.TaskDefKey = field.NewString(tableName, "task_def_key")
	_wfHiTask.TaskType = field.NewString(tableName, "task_type")
	_wfHiTask.Name = field.NewString(tableName, "name")
	_wfHiTask.Description = field.NewString(tableName, "description")
	_wfHiTask.ParentID = field.NewString(tableName, "parent_id")
	_wfHiTask.Status = field.NewString(tableName, "status")
	_wfHiTask.Assignee = field.NewString(tableName, "assignee")
	_wfHiTask.Owner = field.NewString(tableName, "owner")
	_wfHiTask.DueDate = field.NewTime(tableName, "due_date")
	_wfHiTask.Priority = field.NewInt32(tableName, "priority")
	_wfHiTask.FormKey = field.NewString(tableName, "form_key")
	_wfHiTask.Variables = field.NewString(tableName, "variables")
	_wfHiTask.ClaimedAt = field.NewTime(tableName, "claimed_at")
	_wfHiTask.SequenceOrder = field.NewInt32(tableName, "sequence_order")
	_wfHiTask.ApprovalType = field.NewString(tableName, "approval_type")
	_wfHiTask.ApprovalRule = field.NewString(tableName, "approval_rule")
	_wfHiTask.DelegateFrom = field.NewString(tableName, "delegate_from")
	_wfHiTask.DelegateReason = field.NewString(tableName, "delegate_reason")
	_wfHiTask.DelegateTime = field.NewTime(tableName, "delegate_time")
	_wfHiTask.EndedAt = field.NewTime(tableName, "ended_at")
	_wfHiTask.Comment = field.NewString(tableName, "comment")
	_wfHiTask.EndReason = field.NewString(tableName, "end_reason")
	_wfHiTask.Duration = field.NewInt64(tableName, "duration")
	_wfHiTask.TenantID = field.NewString(tableName, "tenant_id")
	_wfHiTask.CreatedBy = field.NewString(tableName, "created_by")
	_wfHiTask.CreatedAt = field.NewTime(tableName, "created_at")
	_wfHiTask.UpdatedBy = field.NewString(tableName, "updated_by")
	_wfHiTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_wfHiTask.fillFieldMap()

	return _wfHiTask
}

type wfHiTask struct {
	wfHiTaskDo

	ALL               field.Asterisk
	ID                field.String // 任务主键UUID
	ProcessInstanceID field.String // 流程实例ID
	ProcessID         field.String // 流程定义ID
	TaskDefKey        field.String // 任务节点ID
	TaskType          field.String // 任务类型
	Name              field.String // 任务名称
	Description       field.String
	ParentID          field.String
	Status            field.String // 状态：created | assigned | pending | active | delegated | suspended | completed | returned | withdrawn | terminated
	Assignee          field.String // 办理人
	Owner             field.String
	DueDate           field.Time
	Priority          field.Int32
	FormKey           field.String
	Variables         field.String // 任务变量
	ClaimedAt         field.Time
	SequenceOrder     field.Int32 // 会签序号（用于顺序会签排序，0表示主任务或非会签任务）
	ApprovalType      field.String
	ApprovalRule      field.String
	DelegateFrom      field.String
	DelegateReason    field.String
	DelegateTime      field.Time
	EndedAt           field.Time   // 完成时间
	Comment           field.String // 处理意见
	EndReason         field.String // 完成/终止原因
	Duration          field.Int64  // 任务耗时（毫秒）
	TenantID          field.String
	CreatedBy         field.String
	CreatedAt         field.Time
	UpdatedBy         field.String
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (w wfHiTask) Table(newTableName string) *wfHiTask {
	w.wfHiTaskDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wfHiTask) As(alias string) *wfHiTask {
	w.wfHiTaskDo.DO = *(w.wfHiTaskDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wfHiTask) updateTableName(table string) *wfHiTask {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.ProcessInstanceID = field.NewString(table, "process_instance_id")
	w.ProcessID = field.NewString(table, "process_id")
	w.TaskDefKey = field.NewString(table, "task_def_key")
	w.TaskType = field.NewString(table, "task_type")
	w.Name = field.NewString(table, "name")
	w.Description = field.NewString(table, "description")
	w.ParentID = field.NewString(table, "parent_id")
	w.Status = field.NewString(table, "status")
	w.Assignee = field.NewString(table, "assignee")
	w.Owner = field.NewString(table, "owner")
	w.DueDate = field.NewTime(table, "due_date")
	w.Priority = field.NewInt32(table, "priority")
	w.FormKey = field.NewString(table, "form_key")
	w.Variables = field.NewString(table, "variables")
	w.ClaimedAt = field.NewTime(table, "claimed_at")
	w.SequenceOrder = field.NewInt32(table, "sequence_order")
	w.ApprovalType = field.NewString(table, "approval_type")
	w.ApprovalRule = field.NewString(table, "approval_rule")
	w.DelegateFrom = field.NewString(table, "delegate_from")
	w.DelegateReason = field.NewString(table, "delegate_reason")
	w.DelegateTime = field.NewTime(table, "delegate_time")
	w.EndedAt = field.NewTime(table, "ended_at")
	w.Comment = field.NewString(table, "comment")
	w.EndReason = field.NewString(table, "end_reason")
	w.Duration = field.NewInt64(table, "duration")
	w.TenantID = field.NewString(table, "tenant_id")
	w.CreatedBy = field.NewString(table, "created_by")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedBy = field.NewString(table, "updated_by")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *wfHiTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wfHiTask) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 31)
	w.fieldMap["id"] = w.ID
	w.fieldMap["process_instance_id"] = w.ProcessInstanceID
	w.fieldMap["process_id"] = w.ProcessID
	w.fieldMap["task_def_key"] = w.TaskDefKey
	w.fieldMap["task_type"] = w.TaskType
	w.fieldMap["name"] = w.Name
	w.fieldMap["description"] = w.Description
	w.fieldMap["parent_id"] = w.ParentID
	w.fieldMap["status"] = w.Status
	w.fieldMap["assignee"] = w.Assignee
	w.fieldMap["owner"] = w.Owner
	w.fieldMap["due_date"] = w.DueDate
	w.fieldMap["priority"] = w.Priority
	w.fieldMap["form_key"] = w.FormKey
	w.fieldMap["variables"] = w.Variables
	w.fieldMap["claimed_at"] = w.ClaimedAt
	w.fieldMap["sequence_order"] = w.SequenceOrder
	w.fieldMap["approval_type"] = w.ApprovalType
	w.fieldMap["approval_rule"] = w.ApprovalRule
	w.fieldMap["delegate_from"] = w.DelegateFrom
	w.fieldMap["delegate_reason"] = w.DelegateReason
	w.fieldMap["delegate_time"] = w.DelegateTime
	w.fieldMap["ended_at"] = w.EndedAt
	w.fieldMap["comment"] = w.Comment
	w.fieldMap["end_reason"] = w.EndReason
	w.fieldMap["duration"] = w.Duration
	w.fieldMap["tenant_id"] = w.TenantID
	w.fieldMap["created_by"] = w.CreatedBy
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_by"] = w.UpdatedBy
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w wfHiTask) clone(db *gorm.DB) wfHiTask {
	w.wfHiTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wfHiTask) replaceDB(db *gorm.DB) wfHiTask {
	w.wfHiTaskDo.ReplaceDB(db)
	return w
}

type wfHiTaskDo struct{ gen.DO }

type IWfHiTaskDo interface {
	gen.SubQuery
	Debug() IWfHiTaskDo
	WithContext(ctx context.Context) IWfHiTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWfHiTaskDo
	WriteDB() IWfHiTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWfHiTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWfHiTaskDo
	Not(conds ...gen.Condition) IWfHiTaskDo
	Or(conds ...gen.Condition) IWfHiTaskDo
	Select(conds ...field.Expr) IWfHiTaskDo
	Where(conds ...gen.Condition) IWfHiTaskDo
	Order(conds ...field.Expr) IWfHiTaskDo
	Distinct(cols ...field.Expr) IWfHiTaskDo
	Omit(cols ...field.Expr) IWfHiTaskDo
	Join(table schema.Tabler, on ...field.Expr) IWfHiTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWfHiTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWfHiTaskDo
	Group(cols ...field.Expr) IWfHiTaskDo
	Having(conds ...gen.Condition) IWfHiTaskDo
	Limit(limit int) IWfHiTaskDo
	Offset(offset int) IWfHiTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWfHiTaskDo
	Unscoped() IWfHiTaskDo
	Create(values ...*model.WfHiTask) error
	CreateInBatches(values []*model.WfHiTask, batchSize int) error
	Save(values ...*model.WfHiTask) error
	First() (*model.WfHiTask, error)
	Take() (*model.WfHiTask, error)
	Last() (*model.WfHiTask, error)
	Find() ([]*model.WfHiTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfHiTask, err error)
	FindInBatches(result *[]*model.WfHiTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WfHiTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWfHiTaskDo
	Assign(attrs ...field.AssignExpr) IWfHiTaskDo
	Joins(fields ...field.RelationField) IWfHiTaskDo
	Preload(fields ...field.RelationField) IWfHiTaskDo
	FirstOrInit() (*model.WfHiTask, error)
	FirstOrCreate() (*model.WfHiTask, error)
	FindByPage(offset int, limit int) (result []*model.WfHiTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWfHiTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wfHiTaskDo) Debug() IWfHiTaskDo {
	return w.withDO(w.DO.Debug())
}

func (w wfHiTaskDo) WithContext(ctx context.Context) IWfHiTaskDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wfHiTaskDo) ReadDB() IWfHiTaskDo {
	return w.Clauses(dbresolver.Read)
}

func (w wfHiTaskDo) WriteDB() IWfHiTaskDo {
	return w.Clauses(dbresolver.Write)
}

func (w wfHiTaskDo) Session(config *gorm.Session) IWfHiTaskDo {
	return w.withDO(w.DO.Session(config))
}

func (w wfHiTaskDo) Clauses(conds ...clause.Expression) IWfHiTaskDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wfHiTaskDo) Returning(value interface{}, columns ...string) IWfHiTaskDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wfHiTaskDo) Not(conds ...gen.Condition) IWfHiTaskDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wfHiTaskDo) Or(conds ...gen.Condition) IWfHiTaskDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wfHiTaskDo) Select(conds ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wfHiTaskDo) Where(conds ...gen.Condition) IWfHiTaskDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wfHiTaskDo) Order(conds ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wfHiTaskDo) Distinct(cols ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wfHiTaskDo) Omit(cols ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wfHiTaskDo) Join(table schema.Tabler, on ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wfHiTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wfHiTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wfHiTaskDo) Group(cols ...field.Expr) IWfHiTaskDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wfHiTaskDo) Having(conds ...gen.Condition) IWfHiTaskDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wfHiTaskDo) Limit(limit int) IWfHiTaskDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wfHiTaskDo) Offset(offset int) IWfHiTaskDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wfHiTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWfHiTaskDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wfHiTaskDo) Unscoped() IWfHiTaskDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wfHiTaskDo) Create(values ...*model.WfHiTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wfHiTaskDo) CreateInBatches(values []*model.WfHiTask, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wfHiTaskDo) Save(values ...*model.WfHiTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wfHiTaskDo) First() (*model.WfHiTask, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfHiTask), nil
	}
}

func (w wfHiTaskDo) Take() (*model.WfHiTask, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfHiTask), nil
	}
}

func (w wfHiTaskDo) Last() (*model.WfHiTask, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfHiTask), nil
	}
}

func (w wfHiTaskDo) Find() ([]*model.WfHiTask, error) {
	result, err := w.DO.Find()
	return result.([]*model.WfHiTask), err
}

func (w wfHiTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfHiTask, err error) {
	buf := make([]*model.WfHiTask, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wfHiTaskDo) FindInBatches(result *[]*model.WfHiTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wfHiTaskDo) Attrs(attrs ...field.AssignExpr) IWfHiTaskDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wfHiTaskDo) Assign(attrs ...field.AssignExpr) IWfHiTaskDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wfHiTaskDo) Joins(fields ...field.RelationField) IWfHiTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wfHiTaskDo) Preload(fields ...field.RelationField) IWfHiTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wfHiTaskDo) FirstOrInit() (*model.WfHiTask, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfHiTask), nil
	}
}

func (w wfHiTaskDo) FirstOrCreate() (*model.WfHiTask, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfHiTask), nil
	}
}

func (w wfHiTaskDo) FindByPage(offset int, limit int) (result []*model.WfHiTask, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wfHiTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wfHiTaskDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wfHiTaskDo) Delete(models ...*model.WfHiTask) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wfHiTaskDo) withDO(do gen.Dao) *wfHiTaskDo {
	w.DO = *do.(*gen.DO)
	return w
}
