// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/rulego/gflow-engine/model"
)

func newWfTask(db *gorm.DB, opts ...gen.DOOption) wfTask {
	_wfTask := wfTask{}

	_wfTask.wfTaskDo.UseDB(db, opts...)
	_wfTask.wfTaskDo.UseModel(&model.WfTask{})

	tableName := _wfTask.wfTaskDo.TableName()
	_wfTask.ALL = field.NewAsterisk(tableName)
	_wfTask.ID = field.NewString(tableName, "id")
	_wfTask.ProcessInstanceID = field.NewString(tableName, "process_instance_id")
	_wfTask.ProcessID = field.NewString(tableName, "process_id")
	_wfTask.TaskType = field.NewString(tableName, "task_type")
	_wfTask.TaskDefKey = field.NewString(tableName, "task_def_key")
	_wfTask.Name = field.NewString(tableName, "name")
	_wfTask.Description = field.NewString(tableName, "description")
	_wfTask.ParentID = field.NewString(tableName, "parent_id")
	_wfTask.Status = field.NewString(tableName, "status")
	_wfTask.Assignee = field.NewString(tableName, "assignee")
	_wfTask.Owner = field.NewString(tableName, "owner")
	_wfTask.DueDate = field.NewTime(tableName, "due_date")
	_wfTask.Priority = field.NewInt32(tableName, "priority")
	_wfTask.FormKey = field.NewString(tableName, "form_key")
	_wfTask.Variables = field.NewString(tableName, "variables")
	_wfTask.ClaimedAt = field.NewTime(tableName, "claimed_at")
	_wfTask.SequenceOrder = field.NewInt32(tableName, "sequence_order")
	_wfTask.ApprovalType = field.NewString(tableName, "approval_type")
	_wfTask.ApprovalRule = field.NewString(tableName, "approval_rule")
	_wfTask.DelegateFrom = field.NewString(tableName, "delegate_from")
	_wfTask.DelegateReason = field.NewString(tableName, "delegate_reason")
	_wfTask.DelegateTime = field.NewTime(tableName, "delegate_time")
	_wfTask.EndedAt = field.NewTime(tableName, "ended_at")
	_wfTask.Comment = field.NewString(tableName, "comment")
	_wfTask.EndReason = field.NewString(tableName, "end_reason")
	_wfTask.Duration = field.NewInt64(tableName, "duration")
	_wfTask.TenantID = field.NewString(tableName, "tenant_id")
	_wfTask.CreatedBy = field.NewString(tableName, "created_by")
	_wfTask.CreatedAt = field.NewTime(tableName, "created_at")
	_wfTask.UpdatedBy = field.NewString(tableName, "updated_by")
	_wfTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_wfTask.fillFieldMap()

	return _wfTask
}

type wfTask struct {
	wfTaskDo

	ALL               field.Asterisk
	ID                field.String // 任务主键UUID
	ProcessInstanceID field.String // 流程实例ID
	ProcessID         field.String
	TaskType          field.String // 任务类型
	TaskDefKey        field.String // 任务节点ID
	Name              field.String
	Description       field.String
	ParentID          field.String // 父任务ID（会签场景）
	Status            field.String // 状态：created | assigned | pending | active | delegated | suspended | completed | returned | withdrawn | terminated
	Assignee          field.String // 当前办理人
	Owner             field.String // 任务拥有人（委托前）
	DueDate           field.Time   // 到期时间
	Priority          field.Int32
	FormKey           field.String
	Variables         field.String // 任务变量
	ClaimedAt         field.Time   // 签收时间
	SequenceOrder     field.Int32  // 会签序号（用于顺序会签排序，0表示主任务或非会签任务）
	ApprovalType      field.String // 审批类型：single、multi、countersign
	ApprovalRule      field.String // 会签规则JSON
	DelegateFrom      field.String // 委托人ID
	DelegateReason    field.String
	DelegateTime      field.Time // 委托时间
	EndedAt           field.Time // 完成时间
	Comment           field.String
	EndReason         field.String
	Duration          field.Int64
	TenantID          field.String // 租户ID
	CreatedBy         field.String
	CreatedAt         field.Time // 创建时间
	UpdatedBy         field.String
	UpdatedAt         field.Time // 最后更新时间

	fieldMap map[string]field.Expr
}

func (w wfTask) Table(newTableName string) *wfTask {
	w.wfTaskDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wfTask) As(alias string) *wfTask {
	w.wfTaskDo.DO = *(w.wfTaskDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wfTask) updateTableName(table string) *wfTask {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.ProcessInstanceID = field.NewString(table, "process_instance_id")
	w.ProcessID = field.NewString(table, "process_id")
	w.TaskType = field.NewString(table, "task_type")
	w.TaskDefKey = field.NewString(table, "task_def_key")
	w.Name = field.NewString(table, "name")
	w.Description = field.NewString(table, "description")
	w.ParentID = field.NewString(table, "parent_id")
	w.Status = field.NewString(table, "status")
	w.Assignee = field.NewString(table, "assignee")
	w.Owner = field.NewString(table, "owner")
	w.DueDate = field.NewTime(table, "due_date")
	w.Priority = field.NewInt32(table, "priority")
	w.FormKey = field.NewString(table, "form_key")
	w.Variables = field.NewString(table, "variables")
	w.ClaimedAt = field.NewTime(table, "claimed_at")
	w.SequenceOrder = field.NewInt32(table, "sequence_order")
	w.ApprovalType = field.NewString(table, "approval_type")
	w.ApprovalRule = field.NewString(table, "approval_rule")
	w.DelegateFrom = field.NewString(table, "delegate_from")
	w.DelegateReason = field.NewString(table, "delegate_reason")
	w.DelegateTime = field.NewTime(table, "delegate_time")
	w.EndedAt = field.NewTime(table, "ended_at")
	w.Comment = field.NewString(table, "comment")
	w.EndReason = field.NewString(table, "end_reason")
	w.Duration = field.NewInt64(table, "duration")
	w.TenantID = field.NewString(table, "tenant_id")
	w.CreatedBy = field.NewString(table, "created_by")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedBy = field.NewString(table, "updated_by")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *wfTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wfTask) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 31)
	w.fieldMap["id"] = w.ID
	w.fieldMap["process_instance_id"] = w.ProcessInstanceID
	w.fieldMap["process_id"] = w.ProcessID
	w.fieldMap["task_type"] = w.TaskType
	w.fieldMap["task_def_key"] = w.TaskDefKey
	w.fieldMap["name"] = w.Name
	w.fieldMap["description"] = w.Description
	w.fieldMap["parent_id"] = w.ParentID
	w.fieldMap["status"] = w.Status
	w.fieldMap["assignee"] = w.Assignee
	w.fieldMap["owner"] = w.Owner
	w.fieldMap["due_date"] = w.DueDate
	w.fieldMap["priority"] = w.Priority
	w.fieldMap["form_key"] = w.FormKey
	w.fieldMap["variables"] = w.Variables
	w.fieldMap["claimed_at"] = w.ClaimedAt
	w.fieldMap["sequence_order"] = w.SequenceOrder
	w.fieldMap["approval_type"] = w.ApprovalType
	w.fieldMap["approval_rule"] = w.ApprovalRule
	w.fieldMap["delegate_from"] = w.DelegateFrom
	w.fieldMap["delegate_reason"] = w.DelegateReason
	w.fieldMap["delegate_time"] = w.DelegateTime
	w.fieldMap["ended_at"] = w.EndedAt
	w.fieldMap["comment"] = w.Comment
	w.fieldMap["end_reason"] = w.EndReason
	w.fieldMap["duration"] = w.Duration
	w.fieldMap["tenant_id"] = w.TenantID
	w.fieldMap["created_by"] = w.CreatedBy
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_by"] = w.UpdatedBy
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w wfTask) clone(db *gorm.DB) wfTask {
	w.wfTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wfTask) replaceDB(db *gorm.DB) wfTask {
	w.wfTaskDo.ReplaceDB(db)
	return w
}

type wfTaskDo struct{ gen.DO }

type IWfTaskDo interface {
	gen.SubQuery
	Debug() IWfTaskDo
	WithContext(ctx context.Context) IWfTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWfTaskDo
	WriteDB() IWfTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWfTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWfTaskDo
	Not(conds ...gen.Condition) IWfTaskDo
	Or(conds ...gen.Condition) IWfTaskDo
	Select(conds ...field.Expr) IWfTaskDo
	Where(conds ...gen.Condition) IWfTaskDo
	Order(conds ...field.Expr) IWfTaskDo
	Distinct(cols ...field.Expr) IWfTaskDo
	Omit(cols ...field.Expr) IWfTaskDo
	Join(table schema.Tabler, on ...field.Expr) IWfTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskDo
	Group(cols ...field.Expr) IWfTaskDo
	Having(conds ...gen.Condition) IWfTaskDo
	Limit(limit int) IWfTaskDo
	Offset(offset int) IWfTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskDo
	Unscoped() IWfTaskDo
	Create(values ...*model.WfTask) error
	CreateInBatches(values []*model.WfTask, batchSize int) error
	Save(values ...*model.WfTask) error
	First() (*model.WfTask, error)
	Take() (*model.WfTask, error)
	Last() (*model.WfTask, error)
	Find() ([]*model.WfTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTask, err error)
	FindInBatches(result *[]*model.WfTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WfTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWfTaskDo
	Assign(attrs ...field.AssignExpr) IWfTaskDo
	Joins(fields ...field.RelationField) IWfTaskDo
	Preload(fields ...field.RelationField) IWfTaskDo
	FirstOrInit() (*model.WfTask, error)
	FirstOrCreate() (*model.WfTask, error)
	FindByPage(offset int, limit int) (result []*model.WfTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWfTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wfTaskDo) Debug() IWfTaskDo {
	return w.withDO(w.DO.Debug())
}

func (w wfTaskDo) WithContext(ctx context.Context) IWfTaskDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wfTaskDo) ReadDB() IWfTaskDo {
	return w.Clauses(dbresolver.Read)
}

func (w wfTaskDo) WriteDB() IWfTaskDo {
	return w.Clauses(dbresolver.Write)
}

func (w wfTaskDo) Session(config *gorm.Session) IWfTaskDo {
	return w.withDO(w.DO.Session(config))
}

func (w wfTaskDo) Clauses(conds ...clause.Expression) IWfTaskDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wfTaskDo) Returning(value interface{}, columns ...string) IWfTaskDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wfTaskDo) Not(conds ...gen.Condition) IWfTaskDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wfTaskDo) Or(conds ...gen.Condition) IWfTaskDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wfTaskDo) Select(conds ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wfTaskDo) Where(conds ...gen.Condition) IWfTaskDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wfTaskDo) Order(conds ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wfTaskDo) Distinct(cols ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wfTaskDo) Omit(cols ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wfTaskDo) Join(table schema.Tabler, on ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wfTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wfTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wfTaskDo) Group(cols ...field.Expr) IWfTaskDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wfTaskDo) Having(conds ...gen.Condition) IWfTaskDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wfTaskDo) Limit(limit int) IWfTaskDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wfTaskDo) Offset(offset int) IWfTaskDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wfTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wfTaskDo) Unscoped() IWfTaskDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wfTaskDo) Create(values ...*model.WfTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wfTaskDo) CreateInBatches(values []*model.WfTask, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wfTaskDo) Save(values ...*model.WfTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wfTaskDo) First() (*model.WfTask, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTask), nil
	}
}

func (w wfTaskDo) Take() (*model.WfTask, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTask), nil
	}
}

func (w wfTaskDo) Last() (*model.WfTask, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTask), nil
	}
}

func (w wfTaskDo) Find() ([]*model.WfTask, error) {
	result, err := w.DO.Find()
	return result.([]*model.WfTask), err
}

func (w wfTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTask, err error) {
	buf := make([]*model.WfTask, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wfTaskDo) FindInBatches(result *[]*model.WfTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wfTaskDo) Attrs(attrs ...field.AssignExpr) IWfTaskDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wfTaskDo) Assign(attrs ...field.AssignExpr) IWfTaskDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wfTaskDo) Joins(fields ...field.RelationField) IWfTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wfTaskDo) Preload(fields ...field.RelationField) IWfTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wfTaskDo) FirstOrInit() (*model.WfTask, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTask), nil
	}
}

func (w wfTaskDo) FirstOrCreate() (*model.WfTask, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTask), nil
	}
}

func (w wfTaskDo) FindByPage(offset int, limit int) (result []*model.WfTask, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wfTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wfTaskDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wfTaskDo) Delete(models ...*model.WfTask) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wfTaskDo) withDO(do gen.Dao) *wfTaskDo {
	w.DO = *do.(*gen.DO)
	return w
}
