// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/rulego/gflow-engine/model"
)

func newWfTaskAssignee(db *gorm.DB, opts ...gen.DOOption) wfTaskAssignee {
	_wfTaskAssignee := wfTaskAssignee{}

	_wfTaskAssignee.wfTaskAssigneeDo.UseDB(db, opts...)
	_wfTaskAssignee.wfTaskAssigneeDo.UseModel(&model.WfTaskAssignee{})

	tableName := _wfTaskAssignee.wfTaskAssigneeDo.TableName()
	_wfTaskAssignee.ALL = field.NewAsterisk(tableName)
	_wfTaskAssignee.ID = field.NewString(tableName, "id")
	_wfTaskAssignee.TaskID = field.NewString(tableName, "task_id")
	_wfTaskAssignee.EntityType = field.NewString(tableName, "entity_type")
	_wfTaskAssignee.EntityID = field.NewString(tableName, "entity_id")
	_wfTaskAssignee.TenantID = field.NewString(tableName, "tenant_id")
	_wfTaskAssignee.CreatedAt = field.NewTime(tableName, "created_at")

	_wfTaskAssignee.fillFieldMap()

	return _wfTaskAssignee
}

type wfTaskAssignee struct {
	wfTaskAssigneeDo

	ALL        field.Asterisk
	ID         field.String
	TaskID     field.String // 任务实例 ID
	EntityType field.String // 实体类型 role/department/person
	EntityID   field.String // 实体 ID（roleId/deptId/userId）
	TenantID   field.String // 租户 ID
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (w wfTaskAssignee) Table(newTableName string) *wfTaskAssignee {
	w.wfTaskAssigneeDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wfTaskAssignee) As(alias string) *wfTaskAssignee {
	w.wfTaskAssigneeDo.DO = *(w.wfTaskAssigneeDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wfTaskAssignee) updateTableName(table string) *wfTaskAssignee {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.TaskID = field.NewString(table, "task_id")
	w.EntityType = field.NewString(table, "entity_type")
	w.EntityID = field.NewString(table, "entity_id")
	w.TenantID = field.NewString(table, "tenant_id")
	w.CreatedAt = field.NewTime(table, "created_at")

	w.fillFieldMap()

	return w
}

func (w *wfTaskAssignee) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wfTaskAssignee) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 6)
	w.fieldMap["id"] = w.ID
	w.fieldMap["task_id"] = w.TaskID
	w.fieldMap["entity_type"] = w.EntityType
	w.fieldMap["entity_id"] = w.EntityID
	w.fieldMap["tenant_id"] = w.TenantID
	w.fieldMap["created_at"] = w.CreatedAt
}

func (w wfTaskAssignee) clone(db *gorm.DB) wfTaskAssignee {
	w.wfTaskAssigneeDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wfTaskAssignee) replaceDB(db *gorm.DB) wfTaskAssignee {
	w.wfTaskAssigneeDo.ReplaceDB(db)
	return w
}

type wfTaskAssigneeDo struct{ gen.DO }

type IWfTaskAssigneeDo interface {
	gen.SubQuery
	Debug() IWfTaskAssigneeDo
	WithContext(ctx context.Context) IWfTaskAssigneeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWfTaskAssigneeDo
	WriteDB() IWfTaskAssigneeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWfTaskAssigneeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWfTaskAssigneeDo
	Not(conds ...gen.Condition) IWfTaskAssigneeDo
	Or(conds ...gen.Condition) IWfTaskAssigneeDo
	Select(conds ...field.Expr) IWfTaskAssigneeDo
	Where(conds ...gen.Condition) IWfTaskAssigneeDo
	Order(conds ...field.Expr) IWfTaskAssigneeDo
	Distinct(cols ...field.Expr) IWfTaskAssigneeDo
	Omit(cols ...field.Expr) IWfTaskAssigneeDo
	Join(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo
	Group(cols ...field.Expr) IWfTaskAssigneeDo
	Having(conds ...gen.Condition) IWfTaskAssigneeDo
	Limit(limit int) IWfTaskAssigneeDo
	Offset(offset int) IWfTaskAssigneeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskAssigneeDo
	Unscoped() IWfTaskAssigneeDo
	Create(values ...*model.WfTaskAssignee) error
	CreateInBatches(values []*model.WfTaskAssignee, batchSize int) error
	Save(values ...*model.WfTaskAssignee) error
	First() (*model.WfTaskAssignee, error)
	Take() (*model.WfTaskAssignee, error)
	Last() (*model.WfTaskAssignee, error)
	Find() ([]*model.WfTaskAssignee, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTaskAssignee, err error)
	FindInBatches(result *[]*model.WfTaskAssignee, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WfTaskAssignee) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWfTaskAssigneeDo
	Assign(attrs ...field.AssignExpr) IWfTaskAssigneeDo
	Joins(fields ...field.RelationField) IWfTaskAssigneeDo
	Preload(fields ...field.RelationField) IWfTaskAssigneeDo
	FirstOrInit() (*model.WfTaskAssignee, error)
	FirstOrCreate() (*model.WfTaskAssignee, error)
	FindByPage(offset int, limit int) (result []*model.WfTaskAssignee, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWfTaskAssigneeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wfTaskAssigneeDo) Debug() IWfTaskAssigneeDo {
	return w.withDO(w.DO.Debug())
}

func (w wfTaskAssigneeDo) WithContext(ctx context.Context) IWfTaskAssigneeDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wfTaskAssigneeDo) ReadDB() IWfTaskAssigneeDo {
	return w.Clauses(dbresolver.Read)
}

func (w wfTaskAssigneeDo) WriteDB() IWfTaskAssigneeDo {
	return w.Clauses(dbresolver.Write)
}

func (w wfTaskAssigneeDo) Session(config *gorm.Session) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Session(config))
}

func (w wfTaskAssigneeDo) Clauses(conds ...clause.Expression) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wfTaskAssigneeDo) Returning(value interface{}, columns ...string) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wfTaskAssigneeDo) Not(conds ...gen.Condition) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wfTaskAssigneeDo) Or(conds ...gen.Condition) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wfTaskAssigneeDo) Select(conds ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wfTaskAssigneeDo) Where(conds ...gen.Condition) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wfTaskAssigneeDo) Order(conds ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wfTaskAssigneeDo) Distinct(cols ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wfTaskAssigneeDo) Omit(cols ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wfTaskAssigneeDo) Join(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wfTaskAssigneeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wfTaskAssigneeDo) RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wfTaskAssigneeDo) Group(cols ...field.Expr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wfTaskAssigneeDo) Having(conds ...gen.Condition) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wfTaskAssigneeDo) Limit(limit int) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wfTaskAssigneeDo) Offset(offset int) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wfTaskAssigneeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wfTaskAssigneeDo) Unscoped() IWfTaskAssigneeDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wfTaskAssigneeDo) Create(values ...*model.WfTaskAssignee) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wfTaskAssigneeDo) CreateInBatches(values []*model.WfTaskAssignee, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wfTaskAssigneeDo) Save(values ...*model.WfTaskAssignee) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wfTaskAssigneeDo) First() (*model.WfTaskAssignee, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskAssignee), nil
	}
}

func (w wfTaskAssigneeDo) Take() (*model.WfTaskAssignee, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskAssignee), nil
	}
}

func (w wfTaskAssigneeDo) Last() (*model.WfTaskAssignee, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskAssignee), nil
	}
}

func (w wfTaskAssigneeDo) Find() ([]*model.WfTaskAssignee, error) {
	result, err := w.DO.Find()
	return result.([]*model.WfTaskAssignee), err
}

func (w wfTaskAssigneeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTaskAssignee, err error) {
	buf := make([]*model.WfTaskAssignee, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wfTaskAssigneeDo) FindInBatches(result *[]*model.WfTaskAssignee, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wfTaskAssigneeDo) Attrs(attrs ...field.AssignExpr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wfTaskAssigneeDo) Assign(attrs ...field.AssignExpr) IWfTaskAssigneeDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wfTaskAssigneeDo) Joins(fields ...field.RelationField) IWfTaskAssigneeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wfTaskAssigneeDo) Preload(fields ...field.RelationField) IWfTaskAssigneeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wfTaskAssigneeDo) FirstOrInit() (*model.WfTaskAssignee, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskAssignee), nil
	}
}

func (w wfTaskAssigneeDo) FirstOrCreate() (*model.WfTaskAssignee, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskAssignee), nil
	}
}

func (w wfTaskAssigneeDo) FindByPage(offset int, limit int) (result []*model.WfTaskAssignee, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wfTaskAssigneeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wfTaskAssigneeDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wfTaskAssigneeDo) Delete(models ...*model.WfTaskAssignee) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wfTaskAssigneeDo) withDO(do gen.Dao) *wfTaskAssigneeDo {
	w.DO = *do.(*gen.DO)
	return w
}
