// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/rulego/gflow-engine/model"
)

func newWfTaskComment(db *gorm.DB, opts ...gen.DOOption) wfTaskComment {
	_wfTaskComment := wfTaskComment{}

	_wfTaskComment.wfTaskCommentDo.UseDB(db, opts...)
	_wfTaskComment.wfTaskCommentDo.UseModel(&model.WfTaskComment{})

	tableName := _wfTaskComment.wfTaskCommentDo.TableName()
	_wfTaskComment.ALL = field.NewAsterisk(tableName)
	_wfTaskComment.ID = field.NewString(tableName, "id")
	_wfTaskComment.TaskID = field.NewString(tableName, "task_id")
	_wfTaskComment.ProcessInstanceID = field.NewString(tableName, "process_instance_id")
	_wfTaskComment.TenantID = field.NewString(tableName, "tenant_id")
	_wfTaskComment.UserID = field.NewString(tableName, "user_id")
	_wfTaskComment.UserName = field.NewString(tableName, "user_name")
	_wfTaskComment.Content = field.NewString(tableName, "content")
	_wfTaskComment.CreatedAt = field.NewTime(tableName, "created_at")

	_wfTaskComment.fillFieldMap()

	return _wfTaskComment
}

type wfTaskComment struct {
	wfTaskCommentDo

	ALL               field.Asterisk
	ID                field.String
	TaskID            field.String // 任务实例 ID
	ProcessInstanceID field.String // 流程实例 ID
	TenantID          field.String // 租户 ID
	UserID            field.String // 评论人 ID
	UserName          field.String // 评论人姓名
	Content           field.String // 评论内容
	CreatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (w wfTaskComment) Table(newTableName string) *wfTaskComment {
	w.wfTaskCommentDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wfTaskComment) As(alias string) *wfTaskComment {
	w.wfTaskCommentDo.DO = *(w.wfTaskCommentDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wfTaskComment) updateTableName(table string) *wfTaskComment {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.TaskID = field.NewString(table, "task_id")
	w.ProcessInstanceID = field.NewString(table, "process_instance_id")
	w.TenantID = field.NewString(table, "tenant_id")
	w.UserID = field.NewString(table, "user_id")
	w.UserName = field.NewString(table, "user_name")
	w.Content = field.NewString(table, "content")
	w.CreatedAt = field.NewTime(table, "created_at")

	w.fillFieldMap()

	return w
}

func (w *wfTaskComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wfTaskComment) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 8)
	w.fieldMap["id"] = w.ID
	w.fieldMap["task_id"] = w.TaskID
	w.fieldMap["process_instance_id"] = w.ProcessInstanceID
	w.fieldMap["tenant_id"] = w.TenantID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["user_name"] = w.UserName
	w.fieldMap["content"] = w.Content
	w.fieldMap["created_at"] = w.CreatedAt
}

func (w wfTaskComment) clone(db *gorm.DB) wfTaskComment {
	w.wfTaskCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wfTaskComment) replaceDB(db *gorm.DB) wfTaskComment {
	w.wfTaskCommentDo.ReplaceDB(db)
	return w
}

type wfTaskCommentDo struct{ gen.DO }

type IWfTaskCommentDo interface {
	gen.SubQuery
	Debug() IWfTaskCommentDo
	WithContext(ctx context.Context) IWfTaskCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWfTaskCommentDo
	WriteDB() IWfTaskCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWfTaskCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWfTaskCommentDo
	Not(conds ...gen.Condition) IWfTaskCommentDo
	Or(conds ...gen.Condition) IWfTaskCommentDo
	Select(conds ...field.Expr) IWfTaskCommentDo
	Where(conds ...gen.Condition) IWfTaskCommentDo
	Order(conds ...field.Expr) IWfTaskCommentDo
	Distinct(cols ...field.Expr) IWfTaskCommentDo
	Omit(cols ...field.Expr) IWfTaskCommentDo
	Join(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo
	Group(cols ...field.Expr) IWfTaskCommentDo
	Having(conds ...gen.Condition) IWfTaskCommentDo
	Limit(limit int) IWfTaskCommentDo
	Offset(offset int) IWfTaskCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskCommentDo
	Unscoped() IWfTaskCommentDo
	Create(values ...*model.WfTaskComment) error
	CreateInBatches(values []*model.WfTaskComment, batchSize int) error
	Save(values ...*model.WfTaskComment) error
	First() (*model.WfTaskComment, error)
	Take() (*model.WfTaskComment, error)
	Last() (*model.WfTaskComment, error)
	Find() ([]*model.WfTaskComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTaskComment, err error)
	FindInBatches(result *[]*model.WfTaskComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WfTaskComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWfTaskCommentDo
	Assign(attrs ...field.AssignExpr) IWfTaskCommentDo
	Joins(fields ...field.RelationField) IWfTaskCommentDo
	Preload(fields ...field.RelationField) IWfTaskCommentDo
	FirstOrInit() (*model.WfTaskComment, error)
	FirstOrCreate() (*model.WfTaskComment, error)
	FindByPage(offset int, limit int) (result []*model.WfTaskComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWfTaskCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wfTaskCommentDo) Debug() IWfTaskCommentDo {
	return w.withDO(w.DO.Debug())
}

func (w wfTaskCommentDo) WithContext(ctx context.Context) IWfTaskCommentDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wfTaskCommentDo) ReadDB() IWfTaskCommentDo {
	return w.Clauses(dbresolver.Read)
}

func (w wfTaskCommentDo) WriteDB() IWfTaskCommentDo {
	return w.Clauses(dbresolver.Write)
}

func (w wfTaskCommentDo) Session(config *gorm.Session) IWfTaskCommentDo {
	return w.withDO(w.DO.Session(config))
}

func (w wfTaskCommentDo) Clauses(conds ...clause.Expression) IWfTaskCommentDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wfTaskCommentDo) Returning(value interface{}, columns ...string) IWfTaskCommentDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wfTaskCommentDo) Not(conds ...gen.Condition) IWfTaskCommentDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wfTaskCommentDo) Or(conds ...gen.Condition) IWfTaskCommentDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wfTaskCommentDo) Select(conds ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wfTaskCommentDo) Where(conds ...gen.Condition) IWfTaskCommentDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wfTaskCommentDo) Order(conds ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wfTaskCommentDo) Distinct(cols ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wfTaskCommentDo) Omit(cols ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wfTaskCommentDo) Join(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wfTaskCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wfTaskCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wfTaskCommentDo) Group(cols ...field.Expr) IWfTaskCommentDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wfTaskCommentDo) Having(conds ...gen.Condition) IWfTaskCommentDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wfTaskCommentDo) Limit(limit int) IWfTaskCommentDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wfTaskCommentDo) Offset(offset int) IWfTaskCommentDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wfTaskCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWfTaskCommentDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wfTaskCommentDo) Unscoped() IWfTaskCommentDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wfTaskCommentDo) Create(values ...*model.WfTaskComment) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wfTaskCommentDo) CreateInBatches(values []*model.WfTaskComment, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wfTaskCommentDo) Save(values ...*model.WfTaskComment) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wfTaskCommentDo) First() (*model.WfTaskComment, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskComment), nil
	}
}

func (w wfTaskCommentDo) Take() (*model.WfTaskComment, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskComment), nil
	}
}

func (w wfTaskCommentDo) Last() (*model.WfTaskComment, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskComment), nil
	}
}

func (w wfTaskCommentDo) Find() ([]*model.WfTaskComment, error) {
	result, err := w.DO.Find()
	return result.([]*model.WfTaskComment), err
}

func (w wfTaskCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WfTaskComment, err error) {
	buf := make([]*model.WfTaskComment, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wfTaskCommentDo) FindInBatches(result *[]*model.WfTaskComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wfTaskCommentDo) Attrs(attrs ...field.AssignExpr) IWfTaskCommentDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wfTaskCommentDo) Assign(attrs ...field.AssignExpr) IWfTaskCommentDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wfTaskCommentDo) Joins(fields ...field.RelationField) IWfTaskCommentDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wfTaskCommentDo) Preload(fields ...field.RelationField) IWfTaskCommentDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wfTaskCommentDo) FirstOrInit() (*model.WfTaskComment, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskComment), nil
	}
}

func (w wfTaskCommentDo) FirstOrCreate() (*model.WfTaskComment, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WfTaskComment), nil
	}
}

func (w wfTaskCommentDo) FindByPage(offset int, limit int) (result []*model.WfTaskComment, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wfTaskCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wfTaskCommentDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wfTaskCommentDo) Delete(models ...*model.WfTaskComment) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wfTaskCommentDo) withDO(do gen.Dao) *wfTaskCommentDo {
	w.DO = *do.(*gen.DO)
	return w
}
